import { Audio } from 'expo-av';
import * as Haptics from 'expo-haptics';
import { Platform } from 'react-native';

export type RarityTier = 'common' | 'rare' | 'epic' | 'legendary' | 'mythic';

/** Preloaded `expo-av` sounds (generated by `scripts/generate-pack-sfx.mjs`). */
let tearSound: Audio.Sound | null = null;
let revealSound: Audio.Sound | null = null;
let hitSound: Audio.Sound | null = null;
let audioInitialized = false;

async function ensureAudioMode() {
  if (audioInitialized) return;
  await Audio.setAudioModeAsync({
    playsInSilentModeIOS: true,
    allowsRecordingIOS: false,
    staysActiveInBackground: false,
    shouldDuckAndroid: true,
    playThroughEarpieceAndroid: false,
  });
  audioInitialized = true;
}

async function loadSounds() {
  await ensureAudioMode();
  if (tearSound && revealSound && hitSound) return;

  try {
    const [t, r, h] = await Promise.all([
      Audio.Sound.createAsync(require('../../assets/sounds/pack_tear.wav')),
      Audio.Sound.createAsync(require('../../assets/sounds/pack_reveal.wav')),
      Audio.Sound.createAsync(require('../../assets/sounds/pack_hit.wav')),
    ]);
    tearSound = t.sound;
    revealSound = r.sound;
    hitSound = h.sound;
  } catch {
    // Missing assets or simulator audio edge cases — haptics still work.
  }
}

async function play(sound: Audio.Sound | null) {
  if (!sound) return;
  try {
    await sound.setPositionAsync(0);
    await sound.playAsync();
  } catch {
    /* ignore */
  }
}

/** Call when the pack opening UI mounts (modal visible). */
export async function initPackOpeningFeedback() {
  await loadSounds();
}

export async function unloadPackOpeningFeedback() {
  try {
    await tearSound?.unloadAsync();
    await revealSound?.unloadAsync();
    await hitSound?.unloadAsync();
  } catch {
    /* ignore */
  }
  tearSound = null;
  revealSound = null;
  hitSound = null;
}

export async function playPackTear() {
  await loadSounds();
  await play(tearSound);
}

export async function playPackReveal() {
  await loadSounds();
  await play(revealSound);
}

export async function playPackHit() {
  await loadSounds();
  await play(hitSound);
}

const runHaptic = (fn: () => Promise<void>) => {
  if (Platform.OS === 'web') return;
  void fn().catch(() => {});
};

/** Modal / rip starts — light tick. */
export function hapticPackEnter() {
  runHaptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light));
}

/** Pre-reveal “whoosh” moment. */
export function hapticPackReveal() {
  runHaptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium));
}

/** Card shown — tier-based punch. */
export function hapticPackResult(tier: RarityTier) {
  if (tier === 'mythic' || tier === 'legendary') {
    runHaptic(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success));
    return;
  }
  if (tier === 'epic' || tier === 'rare') {
    runHaptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium));
    return;
  }
  runHaptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light));
}
